services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: sh -c "npm ci && npm run dev -- -H 0.0.0.0 -p 3000"
