import type { Metadata } from "next";
import { Geist } from "next/font/google";
import AuthSessionSync from "@/src/auth/components/AuthSessionSync";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi">
      <body className={`${geistSans.variable} font-sans antialiased`}>
        <AuthSessionSync />
        {children}
      </body>
    </html>
  );
}
